### ISSUE TITLE
Fork Button without function

### ISSUE THREAD

**Issue by thejockel** [hypriot/rpi-gogs-raspbian#1]
Hi,
the Fork button is without function.
Please fix.

Best regards
Jockel

**Comment by StefanScherer** [comment]
@thejockel please sign in to GitHub and then you can fork repos. It's nothing we can fix.

**Comment by thejockel** [comment]
Hey,
thanks for the fast response time.

The issus is not in github. The isse is in gogs, that I can't any repo.

Best regards
Jockel

**Comment by firecyberice** [comment]
@thejockel We only created the arm compatible binary and a docker image for RPI.
I think it is not an issue of this port.

Have you checked if there is an issue for the FORK button at https://github.com/gogits/gogs/ ?

**Comment by thejockel** [comment]
@firecyberice & @StefanScherer found the problem.
I using a mirror from github and tried to fork "my own" repo.

Forking a repo from an other user is working.
So their isn't an issue.

Best regards
Jockel
